import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './rebuild.css';

const API='https://147258.asro.jp';
async function api(path, options={}) { const r=await fetch(API+path,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options}); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.error||'通信に失敗しました'); return d; }

function Auth({onLogin}){const [register,setRegister]=useState(false),[f,setF]=useState({username:'',password:'',registrationKey:''}),[err,setErr]=useState(''); const submit=async e=>{e.preventDefault();setErr('');try{const d=await api('/api/auth/'+(register?'register':'login'),{method:'POST',body:JSON.stringify(f)});onLogin(d.user)}catch(x){setErr(x.message)}};return <div className="auth"><div className="card"><div className="logo">somenAI</div><h1>{register?'アカウントを作成':'おかえりなさい'}</h1>{register&&<input placeholder="登録キー" value={f.registrationKey} onChange={e=>setF({...f,registrationKey:e.target.value})}/>}<input placeholder="ユーザー名" value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><input placeholder="パスワード（8文字以上）" type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/>{err&&<div className="error">{err}</div>}<button onClick={submit}>{register?'登録する':'ログイン'}</button><button className="link" onClick={()=>setRegister(!register)}>{register?'ログインに戻る':'新規登録はこちら'}</button></div></div>}

function App({user,onLogout}){const [chats,setChats]=useState([]),[active,setActive]=useState(null),[msgs,setMsgs]=useState([]),[text,setText]=useState(''),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[file,setFile]=useState(null); useEffect(()=>{api('/api/chats').then(d=>{setChats(d.chats);if(d.chats[0])setActive(d.chats[0])}).catch(e=>setErr(e.message))},[]);useEffect(()=>{if(active)api('/api/chats/'+active.id+'/messages').then(d=>setMsgs(d.messages)).catch(e=>setErr(e.message));else setMsgs([])},[active]); const fresh=async()=>{try{const d=await api('/api/chats',{method:'POST',body:'{}'});setChats(c=>[d.chat,...c]);setActive(d.chat);setMsgs([])}catch(e){setErr(e.message)}}; const send=async e=>{e.preventDefault();if(!text.trim()||!active||busy)return;const t=text.trim();setText('');setBusy(true);setErr('');setMsgs(m=>[...m,{id:'local'+Date.now(),role:'user',content:t}]);try{const d=await api('/api/chats/'+active.id+'/respond',{method:'POST',body:JSON.stringify({content:t})});setMsgs(m=>[...m,d.message]);if(d.chat){setActive(d.chat);setChats(c=>c.map(x=>x.id===d.chat.id?{...x,...d.chat}:x))}}catch(x){setErr(x.message)}finally{setBusy(false)}}; const pick=e=>{const f=e.target.files?.[0];if(f&&f.type.startsWith('image/'))setFile(f)}; return <div className="app"><aside><div className="sidehead"><div className="logo small">somenAI</div><button onClick={fresh}>＋ 新しいチャット</button></div><div className="chats">{chats.map(c=><button className={active?.id===c.id?'selected':''} onClick={()=>setActive(c)} key={c.id}>{c.title||'新しいチャット'}</button>)}</div><div className="sidebottom"><button>📚 参考資料</button><button>🖼 画像を生成</button><button>⚙ 設定</button><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});onLogout()}}>ログアウト</button></div></aside><main><header><span>{active?.title||'somenAI'}</span><span className="user">{user.username}</span></header><section className="messages">{!active?<div className="welcome"><div className="logo">somenAI</div><h1>何をお手伝いしようか？</h1><button onClick={fresh}>＋ 新しいチャット</button></div>:msgs.map(m=><div className={'msg '+m.role} key={m.id}><b>{m.role==='user'?'あなた':'somenAI'}</b><div>{m.content}</div></div>)}{busy&&<div className="msg assistant"><b>somenAI</b><div className="typing">● ● ●</div></div>}</section>{err&&<div className="error bar">{err}</div>}<form onSubmit={send} className="composer"><label className="plus">＋<input type="file" accept="image/*" onChange={pick}/></label>{file&&<span className="file">📷 {file.name}</span>}<textarea value={text} onChange={e=>setText(e.target.value)} placeholder="メッセージを入力…" disabled={!active||busy}/><button disabled={!active||busy||!text.trim()}>↑</button></form><small>ログイン中: {user.username}</small></main></div>}
function Root(){const [user,setUser]=useState(null),[checking,setChecking]=useState(true);useEffect(()=>{api('/api/me').then(d=>setUser(d.user)).catch(()=>{}).finally(()=>setChecking(false))},[]);if(checking)return <div className="loading"><div className="logo">somenAI</div></div>;return user?<App user={user} onLogout={()=>setUser(null)}/>:<Auth onLogin={setUser}/>}
createRoot(document.getElementById('root')).render(<Root/>);
